### PR TITLE
feat: use tibble if available for zip_list() output

### PR DESCRIPTION
**Pull request by m-muecke**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks a lot!

**Comment by gaborcsardi** [comment]
Ooops, I am sorry, I merged this by mistake, I am afraid I'll have to undo it.

**Comment by gaborcsardi** [comment]
Thanks for the PR, and I am sorry for merging this by mistake.

In general, returning different data types depending on package availability and/or options is fragile. A package that depends on zip may fail or behave differently depending on whether zip is available and whether that option is set.

**Comment by m-muecke** [comment]
> Thanks for the PR, and I am sorry for merging this by mistake.
> 
> In general, returning different data types depending on package availability and/or options is fragile. A package that depends on zip may fail or behave differently depending on whether tibble is available and whether that option is set.

Figured since the same approach is used in the r-lib/fs and other packages, but makes sense.

**Pull request merged**
